In [ ]:
import numpy as np

In [2]:

#activation functions
def sigmoid_activation(weight_sum):
    return 1 / (1 + np.exp(-weight_sum))

def sigmoid_derivative(weight_sum):
    return weight_sum * (1 - weight_sum)


def normal_activation(weight_sum):
    return 1 if weight_sum>0 else 0

In [3]:
raw_data=np.loadtxt('stellar_spectra_data/train.dat')
target_raw=np.loadtxt('stellar_spectra_data/target.dat')
input=np.array(raw_data, dtype=float)
target=np.array(target_raw, dtype=float)



In [4]:
input_min = input.min(axis=0)
input_max = input.max(axis=0)
input = (input - input_min) / (input_max - input_min)

input = np.c_[input,  np.ones(input.shape[0])]  #with bias

In [ ]:
input_size = input.shape[1]  
hidden_size = 10         
output_size = 7 


np.random.seed(42)  
weights_input_hidden = np.random.uniform(-0.5, 0.5, (input_size, hidden_size))
weights_hidden_output = np.random.uniform(-0.5, 0.5, (hidden_size, output_size))

learn_rate = 0.1
epochs = 3

#ONE HOT ENCODING (ACTUALLY THE TARGET IS ALREADY ONE HOT ENCODED)
target_one_hot=target

In [10]:
#main training loop 
for epoch in range(epochs):
    for i in range(input.shape[0]):

        #Front pass oth layer
        hidden_input = np.dot(input[i], weights_input_hidden)
        hidden_output = sigmoid_activation(hidden_input)
        # 1st layer
        final_input = np.dot(hidden_output, weights_hidden_output)
        final_output = sigmoid_activation(final_input)

        error = target_one_hot[i] - final_output
        print(target_one_hot[i], final_output)

        # Back pass from 1st layer to 0th layer
        grad_output = error * sigmoid_derivative(final_output)
        hidden_error = np.dot(grad_output, weights_hidden_output.T)
        grad_hidden = hidden_error * sigmoid_derivative(hidden_output)

        # Weights Update 
        weights_hidden_output += learn_rate * np.outer(hidden_output, grad_output)  
        weights_input_hidden += learn_rate * np.outer(input[i], grad_hidden)  
        

[0. 0. 0. 0. 0. 1. 0.] [0.01112737 0.01494228 0.02155281 0.07743917 0.66106336 0.29294551
 0.02906455]
[0. 1. 0. 0. 0. 0. 0.] [0.05845074 0.63977974 0.28671411 0.11672924 0.06307437 0.02774113
 0.04630741]
[0. 0. 0. 1. 0. 0. 0.] [0.01346445 0.03674488 0.04629704 0.48113037 0.52285145 0.05642709
 0.02574967]
[0. 0. 0. 0. 0. 1. 0.] [0.01076013 0.01508341 0.02023349 0.0731718  0.6265086  0.3206021
 0.03183792]
[0. 0. 0. 1. 0. 0. 0.] [0.01981652 0.0895219  0.10328581 0.65175472 0.21184966 0.01903626
 0.02126044]
[0. 1. 0. 0. 0. 0. 0.] [0.05844233 0.64351645 0.28395906 0.12060176 0.0594049  0.02853745
 0.04629332]
[0. 0. 0. 0. 1. 0. 0.] [0.00941374 0.01427976 0.01548236 0.04426777 0.57152243 0.41906492
 0.04697257]
[0. 0. 0. 0. 0. 1. 0.] [0.00875305 0.01186315 0.00872167 0.0205383  0.31024376 0.61475237
 0.09907546]
[0. 0. 0. 0. 0. 1. 0.] [0.00898217 0.0131216  0.01197275 0.03039294 0.463463   0.51303996
 0.06570341]
[0. 0. 0. 0. 1. 0. 0.] [0.00976821 0.01403035 0.01461355 0.0452519  0.4869

In [ ]:
#VALIDATION PHASE
correct_predict = []
for i in range(input.shape[0]):
    hidden_output = sigmoid_activation(np.dot(input[i], weights_input_hidden))
    final_output = sigmoid_activation(np.dot(hidden_output, weights_hidden_output))
    prediction = np.argmax(final_output) 
    if prediction==np.argmax(target[i]): #AS TARGET WAS ONE HOT ENCODED BUT THE PREDICTION WAS NOT SO I  CONVERTED  ONE HOT ENCODE TARGET TO CLASSES BY ARGMAX
        correct_predict.append(prediction)

accuracy= len(correct_predict) / target.shape[0]
print(accuracy*100)

65.38116591928251
